name: Daily build

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  master:
    uses: 96boards/oe-rpb-manifest/.github/workflows/build-template.yml@qcom/master
    with:
      branch: qcom/master
    secrets: inherit

  dunfell:
    uses: 96boards/oe-rpb-manifest/.github/workflows/build-template.yml@qcom/master
    with:
      branch: qcom/dunfell
    secrets: inherit
